spring.application.name=neulbomgil-backend
server.port=8088
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.url=jdbc:mysql://localhost:3306/neulbomgil?characterEncoding=UTF-8&serverTimezone=UTC
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database=mysql
logging.level.org.hibernate=info
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
vworld.api.key=${API_KEY}

# JWT 설정
application.security.jwt.secret: ${JWT_SECRET}
application.security.jwt.access-token-expiration: 1800000
application.security.jwt.refresh-token-expiration: 604800000

# 메일 설정
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.prop.smtp.auth=true
spring.mail.prop.smtp.starttls.enable=true
spring.mail.username=${MAIL_ID}
spring.mail.password=${MAIL_PASSWORD}